server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /the-race/ {
        alias /usr/share/nginx/html/the-race/;
        try_files $uri $uri/ /the-race/index.html;
    }
}
