server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  absolute_redirect off;

  location /radio/assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
  location = /radio/index.html {
    add_header Cache-Control "no-cache";
  }
  location /radio/ {
    try_files $uri $uri/ /radio/index.html;
  }
  location = / {
    return 302 /radio/;
  }
}
